# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJd8qYloovITo8oguKMyzP3Pdsg-Gtce
"""

import os

print(os.listdir("/content"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/app.py
# 
# import streamlit as st
# import joblib
# import pandas as pd
# 
# # Load trained model
# model = joblib.load("/content/credit_approval_model.pkl")
# 
# # Page configuration
# st.set_page_config(
#     page_title="Credit Card Approval Prediction",
#     page_icon="💳"
# )
# # Title
# st.title("💳 Credit Card Approval Prediction")
# 
# st.write(
#     "Enter the applicant information below "
#     "to predict credit card approval."
# )
# # Input features
# st.subheader("Applicant Information")
# 
# A15 = st.number_input("A15", value=0.0)
# A14 = st.number_input("A14", value=0.0)
# A13 = st.number_input("A13", value=0.0)
# A12 = st.number_input("A12", value=0.0)
# A11 = st.number_input("A11", value=0.0)
# 
# A10 = st.number_input("A10", value=0.0)
# A9 = st.number_input("A9", value=0.0)
# A8 = st.number_input("A8", value=0.0)
# A7 = st.number_input("A7", value=0.0)
# A6 = st.number_input("A6", value=0.0)
# 
# A5 = st.number_input("A5", value=0.0)
# A4 = st.number_input("A4", value=0.0)
# A3 = st.number_input("A3", value=0.0)
# A2 = st.number_input("A2", value=0.0)
# A1 = st.number_input("A1", value=0.0)
# 
# # Create input DataFrame
# input_data = pd.DataFrame([[
#     A15,
#     A14,
#     A13,
#     A12,
#     A11,
#     A10,
#     A9,
#     A8,
#     A7,
#     A6,
#     A5,
#     A4,
#     A3,
#     A2,
#     A1
# ]], columns=[
#     "A15",
#     "A14",
#     "A13",
#     "A12",
#     "A11",
#     "A10",
#     "A9",
#     "A8",
#     "A7",
#     "A6",
#     "A5",
#     "A4",
#     "A3",
#     "A2",
#     "A1"
# ])
# # Prediction
# if st.button("Predict Approval"):
# 
#     prediction = model.predict(input_data)[0]
# 
#     if prediction == 1:
#         st.success("✅ Credit Card Approved")
#     else:
#         st.error("❌ Credit Card Not Approved")
